Migrating Garbage Bin sample from 1.0.0 to 3.1.0
charithag/iot-server-samples pull request #18
Opened 2017-08-04 10:55 UTC by Nirothipan

2017-08-04 11:45 UTC, charithag requested changes
Please reformat the code by removing unnecessary new lines and comments. Also don't use wildcard imports java in classes.

2017-08-04 11:45 UTC, charithag commented on garbagebin/component/api/src/main/java/org/homeautomation/garbagebin/api/DeviceTypeService.java
> +import io.swagger.annotations.*;
Do not use wildcard imports

2017-08-04 11:45 UTC, charithag commented on garbagebin/component/api/src/main/java/org/homeautomation/garbagebin/api/DeviceTypeService.java
> +import javax.ws.rs.*;
Do not use wildcard imports

2017-08-04 11:45 UTC, charithag commented on SenseMe/feature/feature/src/main/resources/agent/SenseMe.ino
> +//const char* ssid = "linksys";
Remove un necessary comments

2017-08-04 11:45 UTC, charithag commented on SenseMe/feature/feature/src/main/resources/agent/SenseMe.ino
> +
Remove unnecessary new lines and format the code

2017-08-04 12:39 UTC, charithag approved these changes

2017-08-04 12:39 UTC, merged

2018-02-28 08:20 UTC, dakshika commented on floor-analytics-demo/building-visualizer/agent/BuildingMonitor/BuildingMonito.ino
> +//const char* ssid = "linksys";
Remove all commented lines

2018-02-28 08:21 UTC, dakshika commented on garbagebin/component/ui/src/main/resources/jaggeryapps/devicemgt/app/units/cdmf.unit.device.garbagebin.operation-bar/operation-bar.hbs
> +            ::-webkit-input-placeholder {
Better to add proper class names and override the styles

2018-02-28 08:22 UTC, dakshika commented on garbagebin/component/ui/src/main/resources/jaggeryapps/devicemgt/app/units/cdmf.unit.device.garbagebin.operation-bar/operation-bar.js
> +       // new Log().info("currentParamList length : " + currentParamList.length);
Remove all commented lines

2018-02-28 08:23 UTC, dakshika reviewed
need to update according to the feedback

2018-02-28 14:52 UTC, Nirothipan commented on floor-analytics-demo/building-visualizer/agent/BuildingMonitor/BuildingMonito.ino
> +//const char* ssid = "linksys";
Fixed with https://github.com/wso2/samples-iots/pull/19

2018-02-28 14:52 UTC, Nirothipan commented on garbagebin/component/ui/src/main/resources/jaggeryapps/devicemgt/app/units/cdmf.unit.device.garbagebin.operation-bar/operation-bar.js
> +       // new Log().info("currentParamList length : " + currentParamList.length);
Fixed with https://github.com/wso2/samples-iots/pull/19